### ISSUE TITLE
php Apcu not installed?

### ISSUE THREAD

**Issue by r100gs** [nextcloud/univention-app#58] opened 2018-06-29 09:50 UTC
Hello,

in my nextcloud app (13.0.4) on Univention (4.3 errata 126) I get info about APCu not installed but should be installed

```
Info	cli	Memcache \OC\Memcache\APCu not available for distributed cache
Info	cli	Memcache \OC\Memcache\APCu not available for local cache
```

Best regards,
Stefan

**Comment by blizzz** [comment] 2018-08-07 15:21
php-apcu is installed and enabled also for CLI. I cannot reproduce this behaviour. 

Did you manually run a specific command before on CLi? Or, where there any modifications to the config.php or the docker containter?

**Comment by blizzz** [comment] 2018-10-11 12:10
As there is no feedback since a while I will close this ticket. If this is still happening please feel free to reopen.

**Closed as completed by blizzz** 2018-10-11 12:10 UTC
